const _ = require('lodash')

const mapKeys = map => (value, key) => map[key] || key
const replaceKeyNames = map => obj => _.mapKeys(obj, mapKeys(map))

/**
 * Strip properties generated by Loki database from object
 * @param {object} object
 * @return {object} object without extra properties generated by Loki database
 */
module.exports.stripLokiProperties = object => _.omit(object, ['meta', '$loki'])

/**
 * Renames field of object
 */
module.exports.idToLokiID = replaceKeyNames({ id: '$loki' })
module.exports.lokiIDToID = replaceKeyNames({ $loki: 'id' })
